# Copyright (c) Microsoft Corporation and contributors. All rights reserved.
# Licensed under the MIT License.

# test-azure-frs pipeline

name: $(Build.BuildId)

schedules:
  - cron: "0 4 * * *"
    displayName: Daily 8pm (PST) builds
    branches:
      include:
        - main
        - next
        - lts
        - release/*
    always: true

trigger:
  branches:
    include:
      - main
      - next
      - lts
      - release/*
  paths:
    include:
      - azure/packages/azure-client
      - packages/framework/loader/container-loader
      - packages/framework/fluid-static
      - packages/drivers/routerlicious-driver
      - packages/dds/map
      - tools/pipelines/test-azure-frs.yml
      - tools/pipelines/templates/include-test-real-service.yml

pr: none

resources:
  pipelines:
    - pipeline: client
      source: Build - client packages
    - pipeline: azure
      source: Build - azure
      trigger:
        branches:
          include:
            - releases/*
            - main
            - next
            - lts

variables:
  - group: prague-key-vault
  - group: fluid-afr-perf-test-keys
  - name: testWorkspace
    value: $(Pipeline.Workspace)/test

stages:
  # Run Azure Client FRS Tests (WestUS2)
  - stage:
    displayName: e2e - frs perf tests (WestUS2)
    dependsOn: []
    jobs:
      - template: templates/include-test-real-service.yml
        parameters:
          poolBuild: Small
          testPackage: "@fluidframework/azure-scenario-runner"
          testWorkspace: ${{ variables.testWorkspace }}
          testCommand: start:westus2
          downloadAzureTestArtifacts: true
          artifactBuildId: $(resources.pipeline.azure.runID)
          env:
            FLUID_TEST_LOGGER_PKG_PATH: ${{ variables.testWorkspace }}/node_modules/@ff-internal/aria-logger # Contains getTestLogger impl to inject
            azure__fluid__relay__service__tenantId: $(fluid-afr-perf-test-westus2-tenantId)
            azure__fluid__relay__service__function__url: $(fluid-afr-perf-test-westus2-function-url)
  # Run Azure Client FRS Tests (WestUS3)
  - stage:
    displayName: e2e - frs perf tests (WestUS3)
    dependsOn: []
    jobs:
      - template: templates/include-test-real-service.yml
        parameters:
          poolBuild: Small
          testPackage: "@fluidframework/azure-scenario-runner"
          testWorkspace: ${{ variables.testWorkspace }}
          testCommand: start:westus3
          downloadAzureTestArtifacts: true
          artifactBuildId: $(resources.pipeline.azure.runID)
          env:
            FLUID_TEST_LOGGER_PKG_PATH: ${{ variables.testWorkspace }}/node_modules/@ff-internal/aria-logger # Contains getTestLogger impl to inject
            azure__fluid__relay__service__tenantId: $(fluid-afr-perf-test-westus3-tenantId)
            azure__fluid__relay__service__function__url: $(fluid-afr-perf-test-westus3-function-url)
  # Run Azure Client FRS Tests (EastUS)
  - stage:
    displayName: e2e - frs perf tests (EastUS)
    dependsOn: []
    jobs:
      - template: templates/include-test-real-service.yml
        parameters:
          poolBuild: Small
          testPackage: "@fluidframework/azure-scenario-runner"
          testWorkspace: ${{ variables.testWorkspace }}
          testCommand: start:eastus
          downloadAzureTestArtifacts: true
          artifactBuildId: $(resources.pipeline.azure.runID)
          env:
            FLUID_TEST_LOGGER_PKG_PATH: ${{ variables.testWorkspace }}/node_modules/@ff-internal/aria-logger # Contains getTestLogger impl to inject
            azure__fluid__relay__service__tenantId: $(fluid-afr-perf-test-eastus-tenantId)
            azure__fluid__relay__service__function__url: $(fluid-afr-perf-test-eastus-function-url)
  # Run Azure Client FRS Tests (Europe)
  - stage:
    displayName: e2e - frs perf tests (WestEurope)
    dependsOn: []
    jobs:
      - template: templates/include-test-real-service.yml
        parameters:
          poolBuild: Small
          testPackage: "@fluidframework/azure-scenario-runner"
          testWorkspace: ${{ variables.testWorkspace }}
          testCommand: start:westeurope
          downloadAzureTestArtifacts: true
          artifactBuildId: $(resources.pipeline.azure.runID)
          env:
            FLUID_TEST_LOGGER_PKG_PATH: ${{ variables.testWorkspace }}/node_modules/@ff-internal/aria-logger # Contains getTestLogger impl to inject
            azure__fluid__relay__service__tenantId: $(fluid-afr-perf-test-westeurope-tenantId)
            azure__fluid__relay__service__function__url: $(fluid-afr-perf-test-westeurope-function-url)
  - stage:
    displayName: e2e - azure client with frs
    dependsOn: []
    jobs:
      - template: templates/include-test-real-service.yml
        parameters:
          poolBuild: Small
          testPackage: "@fluidframework/azure-end-to-end-tests"
          testWorkspace: ${{ variables.testWorkspace }}
          testCommand: test:realsvc:azure
          downloadAzureTestArtifacts: true
          artifactBuildId: $(resources.pipeline.azure.runID)
          env:
            FLUID_TEST_LOGGER_PKG_PATH: ${{ variables.testWorkspace }}/node_modules/@ff-internal/aria-logger # Contains getTestLogger impl to inject
            azure__fluid__relay__service__tenantId: $(azure-fluid-relay-service-tenantId)
            azure__fluid__relay__service__function__url: $(azure-fluid-relay-service-function-url)

  - stage:
    displayName: e2e - azure client with azure local service
    dependsOn: []
    jobs:
      - template: templates/include-test-real-service.yml
        parameters:
          poolBuild: Small
          testPackage: "@fluidframework/azure-end-to-end-tests"
          testWorkspace: ${{ variables.testWorkspace }}
          testCommand: test:realsvc:tinylicious
          downloadAzureTestArtifacts: true
          artifactBuildId: $(resources.pipeline.azure.runID)
          env:
            FLUID_TEST_LOGGER_PKG_PATH: ${{ variables.testWorkspace }}/node_modules/@ff-internal/aria-logger # Contains getTestLogger impl to inject
