# Copyright (c) Microsoft Corporation and contributors. All rights reserved.
# Licensed under the MIT License.

# test-stability pipeline (for the purpose of detecting intermittent and flaky failures)

name: $(Build.BuildId)

trigger: none
pr: none

parameters:
- name: poolBuild
  type: object
  default: Large

- name: buildDirectory
  type: string
  default: .

- name: taskBuild
  type: string
  default: ci:build

- name: taskLint
  type: boolean
  default: false

- name: taskTest
  type: object
  default:
  - ci:test:mocha
  - ci:test:jest
  - ci:test:realsvc:local
  - ci:test:realsvc:tinylicious
  - ci:test:stress:tinylicious
  - test:copyresults

- name: checkoutSubmodules
  type: boolean
  default: true

- name: buildToolsVersionToInstall
  displayName: Fluid build tools version (default = installs version in repo)
  type: string
  default: repo

- name: tagName
  type: string
  default: TestStability

- name: includeInternalVersions
  type: boolean
  default: false

schedules:
  - cron: "00 03 * * SUN"
    displayName: Scheduled Tests weekly at Saturday night
    branches:
      include:
      - main
      - next
    always: true

variables:
- group: prague-key-vault
  # We use 'chalk' to colorize output, which auto-detects color support in the
  # running terminal.  The log output shown in Azure DevOps job runs only has
  # basic ANSI color support though, so force that in the pipeline
- name: stageNames
  value:
  - Test1
  - Test2

stages:
  - ${{ each stageName in variables.stageNames }}:
    - stage:
      displayName: ${{ stageName }}
      dependsOn: []
      jobs:
      - template: templates/include-test-stability.yml
        parameters:
          buildToolsVersionToInstall: ${{ parameters.buildToolsVersionToInstall }}
          buildDirectory: .
          tagName: ${{ parameters.tagName }}
          poolBuild: Large
          checkoutSubmodules: true
          timeoutInMinutes: 360
          taskTest:
          - ci:test:mocha
          - ci:test:jest
          - ci:test:realsvc:local
          - ci:test:realsvc:tinylicious
          - ci:test:stress:tinylicious
          - test:copyresults
