# Copyright (c) Microsoft Corporation and contributors. All rights reserved.
# Licensed under the MIT License.

# test-coverage pipeline (for the purpose of detecting flaky tests)

name: $(Build.BuildId)

trigger: none
pr: none

parameters:
  - name: stageNames
    type: object
    default: 
    - Run 1
    - Run 2
    - Run 3
    - Run 4
    - Run 5


schedules:
  - cron: "46 21 * * FRI"
    displayName: Test Schedule build
    branches:
      include:
      - main
      - next
      - release/*
      - test/clarenceli
    always: true

variables:
- group: prague-key-vault
- name: testWorkspace
  value: $(Pipeline.Workspace)/test

stages:
  - ${{ each value in parameters.stageNames }}:
    - stage:
      displayName: ${{ value }}
      dependsOn: []
      jobs:
      - template: templates/include-test-coverage.yml
        parameters:
          testPackage: "@fluidframework/test-end-to-end-tests"
          testWorkspace: ${{ variables.testWorkspace }}
          testCommand: test:report
          env:
            FLUID_TEST_LOGGER_PKG_PATH: ${{ variables.testWorkspace }}/node_modules/@ff-internal/aria-logger # Contains getTestLogger impl to inject


#schedules:
#  - cron: "0 0 * * *"
#    displayName: Daily midnight build
#    branches:
#      include:
#      - main
#      - next
#      - lts
#      - release/*
