# Copyright (c) Microsoft Corporation and contributors. All rights reserved.
# Licensed under the MIT License.

# test-reliability pipeline (for the purpose of detecting flaky tests)

name: $(Build.BuildId)

trigger: none
pr: none

parameters:
- name: poolBuild
  type: object
  default: Large

- name: stageNames
  type: object
  default:
  - Test1
  - Test2
  - Test3
  - Test4
  - Test5

- name: buildDirectory
  type: string
  default: .

- name: taskBuild
  type: string
  default: ci:build

- name: taskBuildDocs
  type: boolean
  default: false

- name: taskLint
  type: boolean
  default: false

- name: taskTest
  type: object
  default:
  - ci:test:mocha
  - ci:test:jest
  - ci:test:realsvc:local
  - ci:test:realsvc:tinylicious
  - ci:test:stress:tinylicious
  - test:copyresults

- name: checkoutSubmodules
  type: boolean
  default: true

- name: namespace
  type: boolean
  default: true

- name: buildNumberInPatch
  type: string
  default: false

- name: publishOverride
  displayName: Publish Override (default = based on branch)
  type: string
  default: default
  values:
    - default
    - skip
    - force

- name: buildToolsVersionToInstall
  displayName: Fluid build tools version (default = installs version in repo)
  type: string
  default: repo

- name: nonScopedPackages
  displayName: Non-scoped packages to publish
  type: object
  default:
  - fluid-framework

- name: releaseBuildOverride
  displayName: Release Build (default = not released)
  type: string
  default: none
  values:
    - none
    - prerelease
    - release

- name: tagName
  type: string
  default: client

- name: includeInternalVersions
  type: boolean
  default: false

schedules:
  - cron: "15 14 * * FRI"
    displayName: Scheduled Tests
    branches:
      include:
      - main
      - next
    always: true

variables:
- group: prague-key-vault
  # We use 'chalk' to colorize output, which auto-detects color support in the
  # running terminal.  The log output shown in Azure DevOps job runs only has
  # basic ANSI color support though, so force that in the pipeline
- name: FORCE_COLOR
  value: 1
- template: templates/include-vars.yml
  parameters:
    publishOverride: ${{ parameters.publishOverride }}
    releaseBuildOverride: ${{ parameters.releaseBuildOverride }}
    buildNumberInPatch: ${{ parameters.buildNumberInPatch }}
    nonScopedPackages: ${{ parameters.nonScopedPackages }}

stages:
  - ${{ each stageName in parameters.stageNames }}:
    - stage:
      displayName: ${{ stageName }}
      dependsOn: []
      jobs:
      - template: templates/include-test-reliability.yml
        parameters:
          publishOverride: ${{ parameters.publishOverride }}
          releaseBuildOverride: ${{ parameters.releaseBuildOverride }}
          nonScopedPackages: ${{ parameters.nonScopedPackages }}
          buildToolsVersionToInstall: ${{ parameters.buildToolsVersionToInstall }}
          buildDirectory: .
          tagName: client
          poolBuild: Large
          checkoutSubmodules: true
          timeoutInMinutes: 1440
          taskTest:
          - ci:test:mocha
          - ci:test:jest
          - ci:test:realsvc:local
          - ci:test:realsvc:tinylicious
          - ci:test:stress:tinylicious
          - test:copyresults
